### PR TITLE
Add errata file for JNOJIR

### PR DESCRIPTION
**Pull request by matthewtiscareno**
I've added a file for JIRAM in the errata directory, in which I describe the issue that I fixed in order to install volumes JNOJIR_2041 and JNOJIR_2042.

### CODE REVIEW

**Review by rfrenchseti — CHANGES_REQUESTED** [review]
This has been sitting here for a long time waiting for Mark's review, but I'm going to make a comment on it. Generally our errata files have text wrapped at 80 characters, and I think that's a standard we should continue to maintain. The only exceptions are where there are long file paths or sample lines from a data file. Also please look at the existing errata files to see about maintaining the same general format.

**Comment by rfrenchseti** [comment]
Per discussion at the group meeting today 11/21/2023 @matthewtiscareno will discuss this directly with @markshowalter soon.

**Review by markshowalter — COMMENTED** [review]
Fine with me.

**Review by markshowalter — APPROVED** [review]
Approved

**Review by rfrenchseti — APPROVED** [review]

**Comment by rfrenchseti** [comment]
Since no one responded to my original comments, I went ahead and reformatted the errata file to 80 character width before approving and merging.

**Comment by matthewtiscareno** [comment]
Yes, I suppose this is all that was needed.  Thanks for doing this, @rfrenchseti, and I apologize for having let it languish so long.

**Pull request merged**
