### PR TITLE
Adding new previews directory with files to generate previews

### PR DESCRIPTION
**Pull request by mseritan**
Created the "previews" subdirectory of "uranus_occs_earthbased"; it contains two Python scripts to generate the previews for the uranus_occs_earthbased bundleset as well as the font file used for the custom fonts in these previews.

Could not push directly to main due to the error "(protected branch hook declined)".

### CODE REVIEW

**Comment by rfrenchseti** [comment]
Is there a need for the extra `previews` directory? It seems like the code should just be in `previews/uranus/whatever.py`.

**Comment by mseritan** [comment]
@mace-space created the directory rms-data-projects/previews/uranus_occs_earthbased/diagrams for her code and my new directory (rms-data-projects/previews/uranus_occs_earthbased/previews) is meant to mirror that structure. The repeat of the name preview is just because "preview" can be meant in the general sense (both diagrams and line plots) or in the specific sense (line plots only).

**Comment by rfrenchseti** [comment]
Got it. I had forgotten Mia's code was already in the same directory.

**Review by rfrenchseti — APPROVED** [review]

**Comment by matthewtiscareno** [comment]
Mightn't it make more sense to have `rms-data-projects/diagrams/uranus_occs_earthbased` and `rms-data-projects/previews/uranus_occs_earthbased`?  It looks like that might be what we're set up to do in the `pds4-holdings` directory on production.

**Comment by matthewtiscareno** [comment]
https://pds-rings.seti.org/pds4/diagrams/uranus_occs_earthbased

**Comment by rfrenchseti** [comment]
The layout of the source code does not need to match the layout of the bundle. Currently all programs that create either previews or diagrams for any volumes/bundles are under `rms-data-projects/previews`. For example `rms-data-projects/previews/COCIRS` contains scripts to produce both the previews and diagrams for those volumes. We could decide to rearrange all of the sources, but that doesn't seem necessary at the moment and could break existing code.

**Comment by matthewtiscareno** [comment]
Okay

**Pull request merged**
